### ISSUE TITLE
DotProgressBar again becomes visible when fragment or activity resumes

### ISSUE THREAD

**Issue by embydextrous-zz** [silvestrpredko/DotProgressBarExample#6]

**Comment by lawloretienne** [comment]
I am experiencing the same thing.  I am in activity A. I set the visibility of the `DotProgressBar` to Visibility.GONE before going to activity B. Then when i click back to go back to activity A, in onResume() i event tried setting the visibility of the `DotProgressBar` to Visibility.GONE.  But some how the visibility toggles to visible after that point.

**Comment by embydextrous-zz** [comment]
I solved this issue by removimg visibilityListener.

On 2 Dec 2016 00:14, "Etienne Lawlor" <notifications@github.com> wrote:
>
> I am experiencing the same thing. I am in activity A. I set the
visibility of the DotProgressBar to Visibility.GONE before going to
activity B. Then when i click back to go back to activity A, in onResume()
i event tried setting the visibility of the DotProgressBar to
Visibility.GONE. But some how the visibility toggles to visible after that
point.

**Comment by lawloretienne** [comment]
Is the issue here

  @Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    startAnimation();
  }

**Comment by lawloretienne** [comment]
@silvestrpredko  Is the issue here

```java
  @Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    startAnimation();
  }
```

**Comment by silvestrpredko** [comment]
@lawloretienne Hey, I will fix it).

**Comment by lawloretienne** [comment]
@silvestrpredko I'm looking forward to the fix

**Comment by lawloretienne** [comment]
@silvestrpredko Any updates on this?

**Comment by embydextrous-zz** [comment]
@silvestrpredko 

```
@Override
protected void onVisibilityChanged(@NonNull View changedView, int visibility) {
      super.onVisibilityChanged(changedView, visibility);

        /*if (visibility == GONE || visibility == INVISIBLE) {
            stopAnimation();
        } else {
            startAnimation();
        }*/
}
```

This should fix this in DotProgressBar.java

**Comment by silvestrpredko** [comment]
@lawloretienne @embydextrous fixed, please check.
