### ISSUE TITLE
Not displaying progress bar

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [silvestrpredko/DotProgressBarExample#9]
I tried the following code, nothing is being displayed on the screen.
```
new DotProgressBarBuilder(this)
                .setDotAmount(5)
                .setStartColor(Color.BLACK)
                .setAnimationDirection(DotProgressBar.LEFT_DIRECTION)
                .build();
```

**Comment by silvestrpredko** [comment]
@kpradeepkumarreddy I think you didn't add view at the screen.

**Comment by kpradeepkumarreddy** [comment]
yes i did not add in xml. But we should be able to add a view in xml or programmatically right ?
Anyways either in xml or programmatically we will be setting same attributes like dotAmount, startColor, etc. then why to add in xml ? can't i directly create a progressBar programmatically ?

please let me know the usage. Where to add the progressBarView in xml ?

**Comment by silvestrpredko** [comment]
@kpradeepkumarreddy please show the code where you add bar programmatically.

**Comment by kpradeepkumarreddy** [comment]
when i add this view, custom attributes are shown in red color, how to resolve that error ?
```
<com.github.silvestrpredko.dotprogressbar.DotProgressBar
  android:id="@+id/dot_progress_bar"
  android:layout_width="match_parent"
  android:layout_height="50dp"
  custom:amount="5"
  custom:duration="@android:integer/config_mediumAnimTime"
  custom:endColor="@color/light_blue_A400"
  custom:startColor="@color/light_blue_A700"
  custom:animationDirection="left"/>
```

**Comment by kpradeepkumarreddy** [comment]
This is the code i was using to create progressBar programmatically
```
 new DotProgressBarBuilder(DashBoardActivity.this)
                                .setDotAmount(3)
                                .setStartColor(Color.BLUE)
                                .setEndColor(Color.WHITE)
                                .setAnimationTime(2000)
                                .setAnimationDirection(DotProgressBar.LEFT_DIRECTION)
                                .build().setVisibility(View.VISIBLE);
```

**Comment by silvestrpredko** [comment]
@kpradeepkumarreddy DotProgressBarBuilder doesn't add view to activity, you should do it by yourself.

**Comment by kpradeepkumarreddy** [comment]
when i add this view, custom attributes are shown in red color, how to resolve that error ?
```
<com.github.silvestrpredko.dotprogressbar.DotProgressBar
  android:id="@+id/dot_progress_bar"
  android:layout_width="match_parent"
  android:layout_height="50dp"
  custom:amount="5"
  custom:duration="@android:integer/config_mediumAnimTime"
  custom:endColor="@color/light_blue_A400"
  custom:startColor="@color/light_blue_A700"
  custom:animationDirection="left"/>
```

**Comment by silvestrpredko** [comment]
@kpradeepkumarreddy try to use your colors in start and end color attribute

**Comment by kpradeepkumarreddy** [comment]
Please show the usage of your library. What to add in xml ? what to add in program ?
give me some sample code

**Comment by silvestrpredko** [comment]
@kpradeepkumarreddy  repo contains  sample of usage library

**Comment by kpradeepkumarreddy** [comment]
ok. i will try
